robot_cfg:
  kinematics:
    format_version: 2.0
    grasp_contact_link_names: [panda_right_hand, panda_right_leftfinger, panda_right_rightfinger, attached_object_right, panda_left_hand, panda_left_leftfinger, panda_left_rightfinger, attached_object_left]
    asset_root_path: robot/franka_description
    base_link: world_base_link
    collision_link_names: [panda_right_link0, panda_right_link1, panda_right_link2, panda_right_link3, panda_right_link4, panda_right_link5, panda_right_link6, panda_right_link7, panda_right_wrist_camera, panda_right_hand, panda_right_leftfinger, panda_right_rightfinger, attached_object_right, panda_left_link0, panda_left_link1, panda_left_link2, panda_left_link3, panda_left_link4, panda_left_link5, panda_left_link6, panda_left_link7, panda_left_wrist_camera, panda_left_hand, panda_left_leftfinger, panda_left_rightfinger, attached_object_left]
    collision_sphere_buffer: 0.0
    cspace:
      cspace_distance_weight: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      joint_names: [panda_right_joint1, panda_right_joint2, panda_right_joint3, panda_right_joint4, panda_right_joint5, panda_right_joint6, panda_right_joint7, panda_right_finger_joint1, panda_right_finger_joint2, panda_left_joint1, panda_left_joint2, panda_left_joint3, panda_left_joint4, panda_left_joint5, panda_left_joint6, panda_left_joint7, panda_left_finger_joint1, panda_left_finger_joint2]
      max_acceleration: 15.0
      max_jerk: 500.0
      null_space_weight: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      default_joint_position: [0.0, -1.3, 0.0, -2.5, 0.0, 1.5, 0.8, 0.04, 0.04, 0.0, -1.3, 0.0, -2.5, 0.0, 1.5, 0.8, 0.04, 0.04]
    tool_frames: [panda_left_hand_tcp, panda_right_hand_tcp]
    extra_collision_spheres:
      attached_object_right: 4
      attached_object_left: 4
    extra_links:
      attached_object_right:
        fixed_transform: [0, 0, 0, 1, 0, 0, 0]
        joint_name: attach_joint
        joint_type: FIXED
        link_name: attached_object_right
        parent_link_name: panda_right_hand
      attached_object_left:
        fixed_transform: [0, 0, 0, 1, 0, 0, 0]
        joint_name: attach_joint_1
        joint_type: FIXED
        link_name: attached_object_left
        parent_link_name: panda_left_hand
    lock_joints:
      panda_right_finger_joint1: 0.04
      panda_right_finger_joint2: 0.04
      panda_left_finger_joint1: 0.04
      panda_left_finger_joint2: 0.04
    mesh_link_names: [panda_right_link0, panda_right_link1, panda_right_link2, panda_right_link3, panda_right_link4, panda_right_link5, panda_right_link6, panda_right_link7, panda_right_wrist_camera, panda_right_hand, panda_right_leftfinger, panda_right_rightfinger, panda_left_link0, panda_left_link1, panda_left_link2, panda_left_link3, panda_left_link4, panda_left_link5, panda_left_link6, panda_left_link7, panda_left_wrist_camera, panda_left_hand, panda_left_leftfinger, panda_left_rightfinger]
    self_collision_buffer:
      attached_object_right: 0.0
      attached_object_left: 0.0
      panda_right_hand: 0.02
      panda_left_hand: 0.02
      panda_right_leftfinger: 0.01
      panda_left_leftfinger: 0.01
      panda_right_link0: 0.1
      panda_left_link0: 0.1
      panda_right_link1: 0.05
      panda_left_link1: 0.05
      panda_right_link2: 0.0
      panda_left_link2: 0.0
      panda_right_link3: 0.0
      panda_left_link3: 0.0
      panda_right_link4: 0.0
      panda_left_link4: 0.0
      panda_right_link5: 0.0
      panda_left_link5: 0.0
      panda_right_link6: 0.0
      panda_left_link6: 0.0
      panda_right_link7: 0.0
      panda_left_link7: 0.0
      panda_right_rightfinger: 0.01
      panda_left_rightfinger: 0.01
      panda_right_wrist_camera: 0.0
      panda_left_wrist_camera: 0.0
    self_collision_ignore:
      panda_right_base_link: [world_base_link, panda_right_link0]
      world_base_link: [panda_right_base_link, panda_left_base_link]
      panda_right_link0: [panda_right_base_link, panda_right_link1, panda_left_link0, panda_left_link1, panda_left_link2, panda_left_link3, panda_right_link2, panda_right_link3]
      panda_right_link1: [panda_right_link0, panda_right_link2, panda_left_link1, panda_left_link2, panda_left_link4, panda_right_link3, panda_right_link4]
      panda_right_link2: [panda_right_link1, panda_right_link3, panda_left_link2, panda_left_link3, panda_right_link4]
      panda_right_link3: [panda_right_link2, panda_right_link4, panda_left_link3, panda_right_link5, panda_right_link6, panda_right_link7, panda_right_wrist_camera, panda_right_hand]
      panda_right_link4: [panda_right_link3, panda_right_link5, panda_right_link6, panda_right_link7, panda_right_wrist_camera, panda_right_hand]
      panda_right_link5: [panda_right_link4, panda_right_link6]
      panda_right_link6: [panda_right_link5, panda_right_link7, panda_right_wrist_camera, panda_right_hand, panda_right_leftfinger, panda_right_rightfinger]
      panda_right_link7: [panda_right_link6, panda_right_link8, panda_right_gripper, panda_right_hand, panda_right_wrist_camera, panda_right_leftfinger, panda_right_rightfinger]
      panda_right_link8: [panda_right_link7, panda_right_wrist_camera]
      panda_right_wrist_camera: [panda_right_link8, panda_right_hand]
      panda_right_hand: [panda_right_wrist_camera, panda_right_hand_tcp, panda_right_leftfinger, panda_right_rightfinger, panda_right_ee_link]
      panda_right_hand_tcp: [panda_right_hand]
      panda_right_leftfinger: [panda_right_hand, panda_right_wrist_camera]
      panda_right_rightfinger: [panda_right_hand, panda_right_wrist_camera]
      panda_right_ee_link: [panda_right_hand]
      panda_right_gripper: [panda_right_link7]
      panda_left_base_link: [world_base_link, panda_left_link0]
      panda_left_link0: [panda_left_base_link, panda_left_link1, panda_right_link1, panda_left_link2, panda_left_link3, panda_right_link2, panda_right_link3]
      panda_left_link1: [panda_left_link0, panda_left_link2, panda_right_link2, panda_left_link3, panda_left_link4, panda_right_link4]
      panda_left_link2: [panda_left_link1, panda_left_link3, panda_right_link3, panda_left_link4]
      panda_left_link3: [panda_left_link2, panda_left_link4, panda_left_link5, panda_left_link6, panda_left_link7, panda_left_wrist_camera, panda_left_hand]
      panda_left_link4: [panda_left_link3, panda_left_link5, panda_left_link6, panda_left_link7, panda_left_wrist_camera, panda_left_hand]
      panda_left_link5: [panda_left_link4, panda_left_link6]
      panda_left_link6: [panda_left_link5, panda_left_link7, panda_left_wrist_camera, panda_left_hand, panda_left_leftfinger, panda_left_rightfinger]
      panda_left_link7: [panda_left_link6, panda_left_link8, panda_left_gripper, panda_left_hand, panda_left_wrist_camera, panda_left_leftfinger, panda_left_rightfinger]
      panda_left_link8: [panda_left_link7, panda_left_wrist_camera]
      panda_left_wrist_camera: [panda_left_link8, panda_left_hand]
      panda_left_hand: [panda_left_wrist_camera, panda_left_hand_tcp, panda_left_leftfinger, panda_left_rightfinger, panda_left_ee_link]
      panda_left_hand_tcp: [panda_left_hand]
      panda_left_leftfinger: [panda_left_hand, panda_left_wrist_camera]
      panda_left_rightfinger: [panda_left_hand, panda_left_wrist_camera]
      panda_left_ee_link: [panda_left_hand]
      panda_left_gripper: [panda_left_link7]
      attached_object_right: [panda_right_hand, panda_right_leftfinger, panda_right_rightfinger]
      attached_object_left: [panda_left_hand, panda_left_leftfinger, panda_left_rightfinger]
    urdf_path: robot/franka_description/dual_franka_with_camera.urdf
    use_global_cumul: true
    collision_spheres:
      panda_right_link0: [{center: [0.0, 0.0, 0.085], radius: 0.03}, {center: [-0.1, -0.0, 0.085], radius: 0.03}]
      panda_left_link0: [{center: [0.0, 0.0, 0.085], radius: 0.03}, {center: [-0.1, -0.0, 0.085], radius: 0.03}]
      panda_right_link1: [{center: [0.0, -0.08, 0.0], radius: 0.055}, {center: [0.0, -0.03, 0.0], radius: 0.06}, {center: [0.0, 0.0, -0.12], radius: 0.06}, {center: [0.0, 0.0, -0.17], radius: 0.06}]
      panda_left_link1: [{center: [0.0, -0.08, 0.0], radius: 0.055}, {center: [0.0, -0.03, 0.0], radius: 0.06}, {center: [0.0, 0.0, -0.12], radius: 0.06}, {center: [0.0, 0.0, -0.17], radius: 0.06}]
      panda_right_link2: [{center: [0.0, 0.0, 0.03], radius: 0.055}, {center: [0.0, 0.0, 0.08], radius: 0.055}, {center: [0.0, -0.12, 0.0], radius: 0.055}, {center: [0.0, -0.17, 0.0], radius: 0.055}]
      panda_left_link2: [{center: [0.0, 0.0, 0.03], radius: 0.055}, {center: [0.0, 0.0, 0.08], radius: 0.055}, {center: [0.0, -0.12, 0.0], radius: 0.055}, {center: [0.0, -0.17, 0.0], radius: 0.055}]
      panda_right_link3: [{center: [0.0, 0.0, -0.06], radius: 0.05}, {center: [0.0, 0.0, -0.1], radius: 0.06}, {center: [0.08, 0.06, 0.0], radius: 0.052}, {center: [0.08, 0.02, 0.0], radius: 0.052}]
      panda_left_link3: [{center: [0.0, 0.0, -0.06], radius: 0.05}, {center: [0.0, 0.0, -0.1], radius: 0.06}, {center: [0.08, 0.06, 0.0], radius: 0.052}, {center: [0.08, 0.02, 0.0], radius: 0.052}]
      panda_right_link4: [{center: [0.0, 0.0, 0.02], radius: 0.052}, {center: [0.0, 0.0, 0.06], radius: 0.052}, {center: [-0.08, 0.095, 0.0], radius: 0.055}, {center: [-0.08, 0.06, 0.0], radius: 0.052}]
      panda_left_link4: [{center: [0.0, 0.0, 0.02], radius: 0.052}, {center: [0.0, 0.0, 0.06], radius: 0.052}, {center: [-0.08, 0.095, 0.0], radius: 0.055}, {center: [-0.08, 0.06, 0.0], radius: 0.052}]
      panda_right_link5: [{center: [0.0, 0.03, 0.0], radius: 0.05}, {center: [0.0, 0.082, 0.0], radius: 0.05}, {center: [0.0, 0.0, -0.22], radius: 0.05}, {center: [0.0, 0.052, -0.18], radius: 0.04}, {center: [0.01, 0.08, -0.14], radius: 0.022}, {center: [0.01, 0.085, -0.11], radius: 0.022}, {center: [0.01, 0.09, -0.08], radius: 0.022}, {center: [0.01, 0.095, -0.05], radius: 0.022}, {center: [-0.01, 0.08, -0.14], radius: 0.022}, {center: [-0.01, 0.085, -0.11], radius: 0.022}, {center: [-0.01, 0.09, -0.08], radius: 0.022}, {center: [-0.01, 0.095, -0.05], radius: 0.022}, {center: [0.0, -0.009, 0.0], radius: 0.05}]
      panda_left_link5: [{center: [0.0, 0.03, 0.0], radius: 0.05}, {center: [0.0, 0.082, 0.0], radius: 0.05}, {center: [0.0, 0.0, -0.22], radius: 0.05}, {center: [0.0, 0.052, -0.18], radius: 0.04}, {center: [0.01, 0.08, -0.14], radius: 0.022}, {center: [0.01, 0.085, -0.11], radius: 0.022}, {center: [0.01, 0.09, -0.08], radius: 0.022}, {center: [0.01, 0.095, -0.05], radius: 0.022}, {center: [-0.01, 0.08, -0.14], radius: 0.022}, {center: [-0.01, 0.085, -0.11], radius: 0.022}, {center: [-0.01, 0.09, -0.08], radius: 0.022}, {center: [-0.01, 0.095, -0.05], radius: 0.022}, {center: [0.0, -0.009, 0.0], radius: 0.05}]
      panda_right_link6: [{center: [0.085, 0.035, 0.0], radius: 0.045}, {center: [0.085, 0.0, 0.0], radius: 0.045}, {center: [0.085, -0.015, 0.0], radius: 0.045}]
      panda_left_link6: [{center: [0.085, 0.035, 0.0], radius: 0.045}, {center: [0.085, 0.0, 0.0], radius: 0.045}, {center: [0.085, -0.015, 0.0], radius: 0.045}]
      panda_right_link7: [{center: [0.0, 0.0, 0.07], radius: 0.045}, {center: [0.02, 0.04, 0.08], radius: 0.024}, {center: [0.04, 0.02, 0.08], radius: 0.024}, {center: [0.04, 0.06, 0.085], radius: 0.02}, {center: [0.06, 0.04, 0.085], radius: 0.02}]
      panda_left_link7: [{center: [0.0, 0.0, 0.07], radius: 0.045}, {center: [0.02, 0.04, 0.08], radius: 0.024}, {center: [0.04, 0.02, 0.08], radius: 0.024}, {center: [0.04, 0.06, 0.085], radius: 0.02}, {center: [0.06, 0.04, 0.085], radius: 0.02}]
      panda_right_hand: [{center: [0.0, -0.075, 0.01], radius: 0.023}, {center: [0.0, -0.045, 0.01], radius: 0.023}, {center: [0.0, -0.015, 0.01], radius: 0.023}, {center: [0.0, 0.015, 0.01], radius: 0.023}, {center: [0.0, 0.045, 0.01], radius: 0.023}, {center: [0.0, 0.075, 0.01], radius: 0.023}, {center: [0.0, -0.08, 0.03], radius: 0.022}, {center: [0.0, -0.045, 0.03], radius: 0.022}, {center: [0.0, -0.015, 0.03], radius: 0.022}, {center: [0.0, 0.015, 0.03], radius: 0.022}, {center: [0.0, 0.045, 0.03], radius: 0.022}, {center: [0.0, 0.08, 0.03], radius: 0.022}, {center: [0.0, -0.08, 0.045], radius: 0.022}, {center: [0.0, -0.045, 0.045], radius: 0.022}, {center: [0.0, -0.015, 0.045], radius: 0.022}, {center: [0.0, 0.015, 0.045], radius: 0.022}, {center: [0.0, 0.045, 0.045], radius: 0.022}, {center: [0.0, 0.08, 0.045], radius: 0.022}]
      panda_left_hand: [{center: [0.0, -0.075, 0.01], radius: 0.023}, {center: [0.0, -0.045, 0.01], radius: 0.023}, {center: [0.0, -0.015, 0.01], radius: 0.023}, {center: [0.0, 0.015, 0.01], radius: 0.023}, {center: [0.0, 0.045, 0.01], radius: 0.023}, {center: [0.0, 0.075, 0.01], radius: 0.023}, {center: [0.0, -0.08, 0.03], radius: 0.022}, {center: [0.0, -0.045, 0.03], radius: 0.022}, {center: [0.0, -0.015, 0.03], radius: 0.022}, {center: [0.0, 0.015, 0.03], radius: 0.022}, {center: [0.0, 0.045, 0.03], radius: 0.022}, {center: [0.0, 0.08, 0.03], radius: 0.022}, {center: [0.0, -0.08, 0.045], radius: 0.022}, {center: [0.0, -0.045, 0.045], radius: 0.022}, {center: [0.0, -0.015, 0.045], radius: 0.022}, {center: [0.0, 0.015, 0.045], radius: 0.022}, {center: [0.0, 0.045, 0.045], radius: 0.022}, {center: [0.0, 0.08, 0.045], radius: 0.022}]
      panda_right_leftfinger: [{center: [0.0, 0.01, 0.043], radius: 0.011}, {center: [0.0, 0.02, 0.015], radius: 0.011}]
      panda_left_leftfinger: [{center: [0.0, 0.01, 0.043], radius: 0.011}, {center: [0.0, 0.02, 0.015], radius: 0.011}]
      panda_right_rightfinger: [{center: [0.0, -0.01, 0.043], radius: 0.011}, {center: [0.0, -0.02, 0.015], radius: 0.011}]
      panda_left_rightfinger: [{center: [0.0, -0.01, 0.043], radius: 0.011}, {center: [0.0, -0.02, 0.015], radius: 0.011}]
      panda_right_wrist_camera: [{center: [0.097, 0.011, 0.038], radius: 0.017}, {center: [0.097, -0.011, 0.038], radius: 0.017}, {center: [0.079, 0.011, 0.024], radius: 0.018}, {center: [0.079, -0.011, 0.024], radius: 0.018}]
      panda_left_wrist_camera: [{center: [0.097, 0.011, 0.038], radius: 0.017}, {center: [0.097, -0.011, 0.038], radius: 0.017}, {center: [0.079, 0.011, 0.024], radius: 0.018}, {center: [0.079, -0.011, 0.024], radius: 0.018}]
  load_dynamics: false
